### ISSUE TITLE
Wrong Relative path for HDL source on Displayport Gateware

### ISSUE THREAD

**Issue by AEW2015** [opalkelly-opensource/design-resources#1]
https://github.com/opalkelly-opensource/design-resources/blob/27824a5fe8228d6085446430e3608800c21d1404/ExampleProjects/DisplayPort/XEM8320/gateware/vivado_proj_builder.tcl#L128-L129

This should be
```
add_files -norecurse ../../../../HDLComponents/FrontPanelToAxiLiteBridge/gateware/fp_to_axil.v
add_files -norecurse ../../../../HDLComponents/FrontPanelToAxiLiteBridge/gateware/fp_to_axil_iwrap.v
```

**Comment by andersonray** [comment]
Thanks for letting us know. Closed with e4072574528e4037977df017ce860aea524fb646
